const { verifyActionToken, consumeTokenNonce } = require('../security/confirmation');

/**
 * Isolated Payment Simulator (FS-2605 Requirement)
 * 
 * "THE LLM MUST NOT execute payments or directly access payment execution.
 * The payment execution endpoint MUST NOT accept arbitrary LLM output.
 * It should only accept a validated action identifier/token generated by
 * the deterministic security layer."
 */

/**
 * Executes a payment strictly using a cryptographically validated action token
 * @param {string} actionToken - Signed deterministic action token
 * @param {object} db - Database client
 * @returns {Promise<{ success: boolean, transactionId?: string, newBalance?: number, error?: string }>}
 */
async function executePayment(actionToken, db) {
  // 1. Cryptographic validation of action token
  const tokenResult = verifyActionToken(actionToken);
  if (!tokenResult.valid) {
    return {
      success: false,
      error: `Security Authorization Refused: ${tokenResult.reason}`,
      statusCode: 403,
    };
  }

  const payload = tokenResult.payload;
  const { actionId, accountId, recipientId, amount, currency, nonce } = payload;
  const numAmount = parseFloat(amount);

  // 2. Atomic check of current balance
  const accRes = await db.query('SELECT * FROM accounts WHERE id = $1', [accountId]);
  if (accRes.rows.length === 0) {
    return {
      success: false,
      error: `Account '${accountId}' not found`,
      statusCode: 404,
    };
  }

  const account = accRes.rows[0];
  const currentBalance = parseFloat(account.balance);

  if (currentBalance < numAmount) {
    return {
      success: false,
      error: `Insufficient simulated funds. Balance: ₹${currentBalance}, Required: ₹${numAmount}`,
      statusCode: 400,
    };
  }

  const newBalance = parseFloat((currentBalance - numAmount).toFixed(2));
  const transactionId = `TXN_${Date.now()}_${Math.random().toString(36).substring(2, 8).toUpperCase()}`;

  // 3. Ensure proposed action record exists or create one for linking
  const actionRes = await db.query('SELECT * FROM proposed_actions WHERE id = $1', [actionId]);
  let proposedActionId = actionId;
  if (actionRes.rows.length === 0) {
    // Record execution action if proposed externally
    await db.query(`
      INSERT INTO proposed_actions (
        id, user_id, action_type, amount, currency, recipient_id, status
      ) VALUES ($1, $2, 'PAYMENT', $3, $4, $5, 'EXECUTED')
      ON CONFLICT (id) DO UPDATE SET status = 'EXECUTED'
    `, [actionId, payload.userId || account.user_id, numAmount, currency || 'INR', recipientId]);
  } else {
    await db.query("UPDATE proposed_actions SET status = 'EXECUTED' WHERE id = $1", [actionId]);
  }

  // 4. Update account balance
  await db.query('UPDATE accounts SET balance = $1 WHERE id = $2', [newBalance, accountId]);

  // 5. Insert transaction record
  await db.query(`
    INSERT INTO transactions (
      id, proposed_action_id, account_id, recipient_id, amount, currency, status, simulation_note, executed_at
    ) VALUES ($1, $2, $3, $4, $5, $6, 'SUCCESS', 'Executed via validated cryptographic token', CURRENT_TIMESTAMP)
  `, [transactionId, proposedActionId, accountId, recipientId, numAmount, currency || 'INR']);

  // 6. Record in tamper-evident SHA-256 audit log
  const { appendAuditEvent } = require('../audit/auditLog');
  await appendAuditEvent('PAYMENT_EXECUTED', {
    transactionId,
    actionId: proposedActionId,
    accountId,
    recipientId,
    amount: numAmount,
    currency: currency || 'INR',
    previousBalance: currentBalance,
    newBalance,
  }, db);

  // 7. Invalidate nonce to prevent replay attacks
  consumeTokenNonce(nonce);

  return {
    success: true,
    transactionId,
    amount: numAmount,
    currency: currency || 'INR',
    previousBalance: currentBalance,
    newBalance,
    recipientId,
    executedAt: new Date().toISOString(),
    simulationNote: 'Safe simulated banking transaction completed without external bank credentials.',
  };
}

module.exports = {
  executePayment,
};
